# -*- coding: utf-8 -*-
"""analise_pessoas_CFO_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QzDF2j2HITJ7pLutWz9YimzUfne2MKSG
"""

# @title Parâmetros do relatório
mes_referencia = 11  # @param {type:"integer"}
ano_referencia = 2026  # @param {type:"integer"}
exportar_excel = True  # @param {type:"boolean"}

# IDs das planilhas no Google Sheets, agora adaptados para nomes de arquivos CSV no Google Drive
SHEET_FORMIGA = "report_cfo_suap"
SHEET_POLO = "report_polo_suap"
SHEET_AFASTAMENTOS = "report_afastamentos_dw"

COLUNAS_OBRIGATORIAS = [
    "SERVIDOR",
    "MATRICULA",
    "SITUACAO",
    "CARGO EMPREGO",
    "CARGO CLASSE",
    "NIVEL PADRAO",
    "SETOR EXERCICIO",
]

SITUACOES_EXCLUIDAS_RELATORIO = ("APOSENTADO", "SUBSTITUTO", "TEMPORARIO")
SITUACOES_CHEFIA = ("ATIVO PERMANENTE - 01", "COLAB PCCTAE E MAGIS - 41")
SITUACAO_SUBSTITUTO = "CONT.PROF.SUBSTITUTO - 52"
SITUACOES_EXCLUIDAS_PARES = {
    "APOSENTADO - 02",
    "CONT.PROF.SUBSTITUTO - 52",
    "CONT.PROF.TEMPORARIO - 54",
    "INSTITUIDOR PENSAO - 15",
    "ESTAGIARIO - 66",
    "CONTR.PROF.VISITANTE - 53",
}

print(f"Referência: {mes_referencia:02d}/{ano_referencia}")

DRIVE_FOLDER_ID = '1KKvpnxc7hvCvlTgYoo9qCvUJdYO5mqfU' # @param {type:"string"}
# Substitua 'YOUR_GOOGLE_DRIVE_FOLDER_ID_HERE' pelo ID da sua pasta no Google Drive.
# Para encontrar o ID da pasta, abra a pasta no Google Drive no seu navegador, o ID estará na URL.
# Exemplo de URL: https://drive.google.com/drive/folders/1abcDEfGhIjKLMnOpQR_s_TuV_WxYz
# O ID da pasta seria '1abcDEfGhIjKLMnOpQR_s_TuV_WxYz'.
# Se quiser procurar em todo o seu Drive (pode ser lento), defina DRIVE_FOLDER_ID = None

# @title Carregamento dos dados
from google.colab import drive, auth
import google.auth
from google.auth.transport.requests import Request
import io
import requests
import pandas as pd
from googleapiclient.discovery import build

drive.mount("/content/drive")
auth.authenticate_user()
creds, _ = google.auth.default()
creds.refresh(Request())

def load_csv_from_drive_by_name(file_name, creds, nome="planilha", folder_id=None):
    """
    Loads a CSV file (or Google Sheet exported as CSV) from Google Drive by its name into a pandas DataFrame.
    """
    try:
        service = build('drive', 'v3', credentials=creds)

        query = f"name = '{file_name}' and trashed = false"
        if folder_id:
            query = f"'{folder_id}' in parents and {query}"

        results = service.files().list(q=query, fields="files(id, name, mimeType)").execute()
        items = results.get('files', [])

        if not items:
            print(f"[ERRO] {nome}: Nenhum arquivo '{file_name}' encontrado no Google Drive.")
            return pd.DataFrame()
        elif len(items) > 1:
            print(f"[AVISO] {nome}: Múltiplos arquivos '{file_name}' encontrados. Usando o primeiro: '{items[0]['name']}' (ID: {items[0]['id']}).")
            file_id = items[0]['id']
            file_mime_type = items[0]['mimeType']
        else:
            file_id = items[0]['id']
            file_mime_type = items[0]['mimeType']
            print(f"[OK] {nome}: Arquivo '{file_name}' (ID: {file_id}, MIME Type: {file_mime_type}) encontrado.")

        # Download the file content, handling Google Sheets specifically
        if file_mime_type == 'application/vnd.google-apps.spreadsheet':
            # Export Google Sheet as CSV
            request = service.files().export_media(
                fileId=file_id, mimeType='text/csv')
        elif file_mime_type == 'text/csv':
            # Download regular CSV file
            request = service.files().get_media(fileId=file_id)
        else:
            print(f"[ERRO] {nome}: Tipo de arquivo '{file_mime_type}' não suportado. Esperava 'text/csv' ou 'application/vnd.google-apps.spreadsheet'.")
            return pd.DataFrame()

        downloaded_content = io.BytesIO(request.execute())

        df = pd.read_csv(downloaded_content)
        print(f"[OK] {nome}: {len(df)} linhas, {len(df.columns)} colunas")
        return df

    except Exception as exc:
        print(f"[ERRO] Falha ao carregar {nome} do Drive: {exc}")
        return pd.DataFrame()


df_formiga = load_csv_from_drive_by_name(SHEET_FORMIGA, creds, "Formiga", folder_id=DRIVE_FOLDER_ID)
df_poloinovacao = load_csv_from_drive_by_name(SHEET_POLO, creds, "Polo Inovação", folder_id=DRIVE_FOLDER_ID)
afastamentos_raw = load_csv_from_drive_by_name(SHEET_AFASTAMENTOS, creds, "Afastamentos", folder_id=DRIVE_FOLDER_ID)

df_bruto = pd.concat([df_formiga, df_poloinovacao], ignore_index=True)
if "MATRICULA" in df_bruto.columns:
    df = df_bruto.drop_duplicates(subset=["MATRICULA"], keep="last")
else:
    df = df_bruto.drop_duplicates()

print(f"Servidores após concatenar/deduplicar: {len(df)}")

# @title Normalizações
from pandas.api.types import is_datetime64_any_dtype


def validar_colunas(df, obrigatorias):
    faltando = [c for c in obrigatorias if c not in df.columns]
    if faltando:
        print("[AVISO] Colunas obrigatórias ausentes:", faltando)
        print("Colunas encontradas:", list(df.columns))
    extras_uteis = [
        c for c in ["DATA ULTIMA PROGRESSAO", "DATA POSSE NO CARGO", "FUNCAO DISPLAY", "CPF"]
        if c not in df.columns
    ]
    if extras_uteis:
        print("[AVISO] Colunas opcionais ausentes:", extras_uteis)
    return not faltando


def normalizar_servidores(df):
    out = df.copy()
    out.columns = [str(c).strip() for c in out.columns]

    if "SERVIDOR" in out.columns:
        out["SERVIDOR"] = out["SERVIDOR"].astype(str).str.strip()

    date_cols = [
        "DATA POSSE NO CARGO",
        "DATA ULTIMA PROGRESSAO",
        "DATA DE NASCIMENTO",
        "CARGO EMPREGO DATA SAIDA",
    ]
    for col in date_cols:
        if col in out.columns and not is_datetime64_any_dtype(out[col]):
            out[col] = pd.to_datetime(out[col], errors="coerce", dayfirst=True)

    for col in ["SEXO", "SITUACAO", "TITULACAO", "APOSENTADORIA"]:
        if col in out.columns:
            out[col] = out[col].astype(str).str.strip()

    if "MATRICULA" in out.columns:
        out["MATRICULA_NORMALIZADA"] = (
            out["MATRICULA"].astype(str).str.strip().str.replace(r"\.0$", "", regex=True)
        )

    if "SETOR EXERCICIO" in out.columns:
        out["SETOR_NORM"] = out["SETOR EXERCICIO"].astype(str).str.strip().str.upper()
    else:
        out["SETOR_NORM"] = ""

    return out


def normalizar_afastamentos(afastamentos_df):
    if afastamentos_df is None or afastamentos_df.empty:
        return pd.DataFrame()

    out = afastamentos_df.copy()
    out.columns = [str(c).strip().upper() for c in out.columns]

    for col in ["DIA INICIO AFASTAMENTO", "DIA FIM AFASTAMENTO", "DATA INÍCIO", "DATA FIM"]:
        if col in out.columns:
            out[col] = pd.to_datetime(out[col], errors="coerce", dayfirst=True)

    if "VÍNCULO SERVIDOR" in out.columns:
        out["MATRICULA_EXTRAIDA"] = (
            out["VÍNCULO SERVIDOR"]
            .astype(str)
            .str.strip()
            .str.replace(r"\.0$", "", regex=True)
            .apply(lambda x: x.split("-")[-1].strip() if "-" in x else x)
        )
    elif "MATRICULA" in out.columns:
        out["MATRICULA_EXTRAIDA"] = out["MATRICULA"].astype(str).str.strip()
    else:
        out["MATRICULA_EXTRAIDA"] = ""

    return out


ok = validar_colunas(df, COLUNAS_OBRIGATORIAS)
df = normalizar_servidores(df)

# Excluir pessoas com CODIGO VAGA igual a 0 logo após a normalização do df
if "CODIGO VAGA" in df.columns:
    initial_count = len(df)
    # Convert 'CODIGO VAGA' to numeric, coercing errors to NaN
    df['CODIGO VAGA_NUM'] = pd.to_numeric(df['CODIGO VAGA'], errors='coerce')
    # Filter out rows where the numeric 'CODIGO VAGA' is 0
    df = df[df['CODIGO VAGA_NUM'].fillna(-1) != 0] # Fill NaN with -1 to keep them if they couldn't be converted
    df = df.drop(columns=['CODIGO VAGA_NUM']) # Drop the temporary column
    if len(df) < initial_count:
        print(f"[FILTRO] Excluídos {initial_count - len(df)} registros com 'CODIGO VAGA' = 0.")


afastamentos = normalizar_afastamentos(afastamentos_raw)

n_prog = df["DATA ULTIMA PROGRESSAO"].notna().sum() if "DATA ULTIMA PROGRESSAO" in df.columns else 0
n_posse = df["DATA POSSE NO CARGO"].notna().sum() if "DATA POSSE NO CARGO" in df.columns else 0
print(f"Datas de última progressão válidas: {n_prog}")
print(f"Datas de posse válidas: {n_posse}")
print(f"Afastamentos normalizados: {len(afastamentos)}")
print("Validação de colunas:", "OK" if ok else "INCOMPLETA")

# @title Funções
import datetime
import re
import textwrap
from collections import defaultdict
from dateutil.relativedelta import relativedelta

PCCTAE_PADRAO_MAX = 19  # Lei 15.141/2025 (antes era 16)


def limpar_classe(classe):
    """Remove a palavra CLASSE e devolve só o código (C, D, T, DIV...)."""
    if pd.isna(classe):
        return "?"
    s = str(classe).strip().upper()
    s = s.replace("CLASSE", " ").replace("-", " ")
    partes = [p for p in s.split() if p]
    return partes[-1] if partes else "?"


def extrair_numero(valor):
    digitos = "".join(ch for ch in str(valor) if ch.isdigit())
    return int(digitos) if digitos else 0


def extrair_padrao(valor, maximo=PCCTAE_PADRAO_MAX):
    """
    Extrai o padrão de vencimento.
    Se vier composto (ex.: 409, 202), tenta os últimos 2 dígitos.
    """
    n = extrair_numero(valor)
    if 1 <= n <= maximo:
        return n
    s = "".join(ch for ch in str(valor) if ch.isdigit())
    if len(s) >= 2:
        n2 = int(s[-2:])
        if 1 <= n2 <= maximo:
            return n2
    if len(s) >= 1:
        n1 = int(s[-1])
        if 1 <= n1 <= maximo:
            return n1
    return n if n else 0


def aniversario_seguro(base, ano):
    """Evita ValueError em 29/02 de ano não-bissexto."""
    try:
        return datetime.date(ano, base.month, base.day)
    except ValueError:
        return datetime.date(ano, 2, 28)


def tem_doutorado(titulacao):
    if pd.isna(titulacao):
        return False
    t = str(titulacao).strip().upper()
    chaves = ("DOUTORADO", "DOUTOR", "DR.", "DR ", "PHD", "PH.D", "PH. D")
    return any(k in t for k in chaves)


def calcular_proximo_posicionamento(classe, padrao, cargo):
    classe_str = str(classe).strip().upper() if pd.notna(classe) else ""
    classe_cod = limpar_classe(classe)
    is_ebtt = "PROFESSOR" in str(cargo).upper()
    padrao_num = extrair_padrao(padrao, maximo=4 if is_ebtt else PCCTAE_PADRAO_MAX)

    # Já no topo EBTT
    if classe_cod in {"T", "TITULAR"} or "TITULAR" in classe_str:
        return "TITULAR"

    if is_ebtt:
        if padrao_num >= 4:
            if "DIV" in classe_str or classe_cod in {"C", "DIV"}:
                return "TITULAR"
            # Alterado: 'B' agora progride para DIII-1
            if "DIII" in classe_str or classe_cod in {"DIII"}:
                return "DIV-1"
            if "DII" in classe_str or "DI" in classe_str or classe_cod in {"A", "B", "DI", "DII"}:
                return "DIII-1"
            return "TITULAR"

        if "DIV" in classe_str or classe_cod == "DIV":
            base = "DIV"
        elif "DIII" in classe_str or classe_cod == "DIII":
            base = "DIII"
        elif "DII" in classe_str or classe_cod == "DII":
            base = "DII"
        elif "DI" in classe_str or classe_cod == "DI":
            base = "DI"
        else:
            base = classe_cod
        return f"{base}-{padrao_num + 1}"

    # PCCTAE: padrões 1..19 (Lei 15.141/2025)
    if padrao_num >= PCCTAE_PADRAO_MAX:
        return f"{classe_cod}-{PCCTAE_PADRAO_MAX}"
    return f"{classe_cod}-{padrao_num + 1}"


def posicionamento_atual(classe, padrao, cargo=""):
    c_atual = limpar_classe(classe)
    if c_atual in {"T", "TITULAR"} or "TITULAR" in str(classe).upper():
        return "TITULAR"
    is_ebtt = "PROFESSOR" in str(cargo).upper()
    p_atual = extrair_padrao(padrao, maximo=4 if is_ebtt else PCCTAE_PADRAO_MAX)
    return f"{c_atual}-{p_atual}"


def classificar_progressao(pos_atual, pos_nova, db, prox_data, titulacao, cargo):
    """
    Retorna (pos_nova_ajustada, efeitos_financeiros, observacao)
    efeitos_financeiros: 'Sim' | 'Não'
    """
    is_ebtt = "PROFESSOR" in str(cargo).upper()

    # 1) Já no topo (Titular ou PCCTAE-19)
    if str(pos_atual).upper() == "TITULAR" or pos_atual == pos_nova:
        label = pos_atual
        return (
            f"JÁ NO TOPO ({label})",
            "Não",
            "Somente Avaliação de Desempenho. Sem efeitos financeiros — final de carreira",
        )

    # 2) Promoção a Titular (ex.: C-4 / DIV-4 → TITULAR)
    if is_ebtt and str(pos_nova).upper() == "TITULAR":
        tempo_ok = False
        if pd.notna(db):
            base = db.date() if hasattr(db, "date") else db
            tempo_ok = relativedelta(prox_data, base).years >= 2

        doutorado_ok = tem_doutorado(titulacao)
        pendencias = []
        if not tempo_ok:
            pendencias.append("tempo mínimo de 2 anos no nível atual")
        if not doutorado_ok:
            pendencias.append("diploma de doutorado")

        if pendencias:
            return (
                f"{pos_nova} (PENDENTE)",
                "Não",
                "Somente Avaliação de Desempenho. Falta: " + "; ".join(pendencias),
            )
        return (
            pos_nova,
            "Não",
            "Somente Avaliação de Desempenho. Promoção a Titular — sem efeitos financeiros (requisitos atendidos)",
        )

    # 3) Progressão ordinária
    return (pos_nova, "Sim", "Progressão com efeitos financeiros")


def formatar_funcao_display(funcao_str):
    if pd.isna(funcao_str):
        return ""
    match = re.match(r"([A-Z]+)(\d+)", str(funcao_str).split(" - ")[0].strip().upper())
    if match:
        return f"{match.group(1)}-{int(match.group(2))}"
    return str(funcao_str).split(" - ")[0].strip()


def construir_indice_setores(df_completo):
    indice = {}
    if "SETOR_NORM" not in df_completo.columns:
        return indice
    for setor, grupo in df_completo.groupby("SETOR_NORM", dropna=False):
        if not setor or setor in {"NAN", "NONE"}:
            continue
        indice[setor] = grupo.copy()
    return indice


def identificar_chefia_e_pares(setor, indice_setores, servidor_atual=None):
    if pd.isna(setor) or str(setor).strip() == "":
        return "N/A", "Nenhum"

    setor_str = str(setor).strip().upper()
    df_setor = indice_setores.get(setor_str)
    if df_setor is None or df_setor.empty:
        return "N/A", "Nenhum"

    funcao = df_setor.get("FUNCAO DISPLAY", pd.Series("", index=df_setor.index))
    valid_funcao = funcao.astype(str).str.upper().str.startswith(("FG", "CD"), na=False)
    situacao = df_setor.get("SITUACAO", pd.Series("", index=df_setor.index)).astype(str).str.strip().str.upper()

    chefes_df = df_setor[valid_funcao & situacao.isin(SITUACOES_CHEFIA)]
    substitutos_df = df_setor[valid_funcao & (situacao == SITUACAO_SUBSTITUTO)]

    chefes = sorted({
        f"{r['SERVIDOR']} ({formatar_funcao_display(r.get('FUNCAO DISPLAY'))})"
        for _, r in chefes_df.iterrows()
    })
    subst = sorted({
        f"{r['SERVIDOR']} ({formatar_funcao_display(r.get('FUNCAO DISPLAY'))})"
        for _, r in substitutos_df.iterrows()
    })

    partes = []
    if chefes:
        partes.append(", ".join(chefes))
    if subst:
        partes.append(f"Substitutos: {', '.join(subst)}")
    chefia_str = "; ".join(partes) if partes else "N/A"

    pares_df = df_setor[(~valid_funcao) & (~situacao.isin(SITUACOES_EXCLUIDAS_PARES))]
    if servidor_atual is not None:
        pares_df = pares_df[pares_df["SERVIDOR"].astype(str).str.upper() != str(servidor_atual).upper()]
    pares_list = sorted(pares_df["SERVIDOR"].dropna().astype(str).unique().tolist())
    return chefia_str, ", ".join(pares_list) if pares_list else "Nenhum"


def construir_indice_afastamentos(afastamentos_df):
    indice = defaultdict(list)
    if afastamentos_df is None or afastamentos_df.empty or "MATRICULA_EXTRAIDA" not in afastamentos_df.columns:
        return indice

    col_tipo = next((c for c in ["COD AFASTAMENTO", "OCORRÊNCIA", "OCORRENCIA"] if c in afastamentos_df.columns), None)
    col_ini = next((c for c in ["DIA INICIO AFASTAMENTO", "DATA INÍCIO", "DATA INICIO"] if c in afastamentos_df.columns), None)
    col_fim = next((c for c in ["DIA FIM AFASTAMENTO", "DATA FIM"] if c in afastamentos_df.columns), None)

    for _, row in afastamentos_df.iterrows():
        mat = str(row.get("MATRICULA_EXTRAIDA", "")).strip()
        if not mat:
            continue
        indice[mat].append({
            "tipo": str(row.get(col_tipo) if col_tipo else "Ocorrência").strip() or "Ocorrência",
            "inicio": row.get(col_ini),
            "fim": row.get(col_fim),
        })
    return indice


def _para_data(valor):
    if pd.isna(valor):
        return None
    if hasattr(valor, "date"):
        try:
            return valor.date()
        except Exception:
            pass
    ts = pd.to_datetime(valor, errors="coerce", dayfirst=True)
    if pd.isna(ts):
        return None
    return ts.date()


def get_afastamentos_info(matricula, inicio_intersticio, fim_intersticio, indice_afast):
    registros = indice_afast.get(str(matricula).strip(), [])
    if not registros:
        return "Nenhum", "Nenhum"

    validos, outros = [], []
    for item in registros:
        d_ini = _para_data(item["inicio"])
        d_fim = _para_data(item["fim"])
        if d_ini is None or d_fim is None:
            continue
        delta = (min(fim_intersticio, d_fim) - max(inicio_intersticio, d_ini)).days + 1
        per_str = f"{d_ini.strftime('%d/%m/%Y')} a {d_fim.strftime('%d/%m/%Y')}"
        texto = f"{item['tipo']} ({per_str}"
        if delta > 0:
            validos.append(f"{texto} | {delta} dias no interstício)")
        else:
            outros.append(f"{texto})")

    af_periodo = "<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• ".join(validos) if validos else "Nenhum"
    af_outros = "<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• ".join(outros) if outros else "Nenhum"
    return af_periodo, af_outros


def senha_cpf(cpf):
    if pd.isna(cpf):
        return "000"
    apenas = str(cpf).strip().replace(".", "").replace("-", "")
    return (apenas[:3] or "000")


def gerar_registros_progressao(df, mes, ano, afastamentos_df):
    indice_setores = construir_indice_setores(df)
    indice_afast = construir_indice_afastamentos(afastamentos_df)
    registros = []

    for _, row in df.iterrows():
        situacao = str(row.get("SITUACAO", "")).upper()
        if any(x in situacao for x in SITUACOES_EXCLUIDAS_RELATORIO):
            continue

        db = row.get("DATA ULTIMA PROGRESSAO")
        if pd.isna(db):
            db = row.get("DATA POSSE NO CARGO")
        if pd.isna(db) or int(db.month) != int(mes):
            continue

        cargo = row.get("CARGO EMPREGO", "")
        anos_ciclo = 2 if "PROFESSOR" in str(cargo).upper() else 1
        if (ano - int(db.year)) % anos_ciclo != 0:
            continue

        prox_data = aniversario_seguro(db, ano)
        ini_int = prox_data - relativedelta(years=anos_ciclo)
        fim_int = prox_data - relativedelta(days=1)

        matricula = str(row.get("MATRICULA_NORMALIZADA", row.get("MATRICULA", ""))).strip()
        af_per, af_out = get_afastamentos_info(matricula, ini_int, fim_int, indice_afast)

        classe = row.get("CARGO CLASSE", "")
        padrao = row.get("NIVEL PADRAO", "")
        pos_atual = posicionamento_atual(classe, padrao, cargo)
        pos_nova = calcular_proximo_posicionamento(classe, padrao, cargo)

        pos_nova, efeitos_fin, observacao = classificar_progressao(
            pos_atual=pos_atual,
            pos_nova=pos_nova,
            db=db,
            prox_data=prox_data,
            titulacao=row.get("TITULACAO", ""),
            cargo=cargo,
        )

        funcao = row.get("FUNCAO DISPLAY")
        direcao = (
            str(funcao)
            if pd.notna(funcao) and str(funcao).strip() not in {"", "-", "nan", "None"}
            else "Não ocupou"
        )
        chefes_str, pares_str = identificar_chefia_e_pares(
            row.get("SETOR EXERCICIO"), indice_setores, row.get("SERVIDOR")
        )

        registros.append({
            "servidor": str(row.get("SERVIDOR", "")).upper(),
            "siape": row.get("MATRICULA"),
            "cargo": cargo,
            "intersticio_inicio": ini_int,
            "intersticio_fim": fim_int,
            "efeitos": prox_data,
            "pos_atual": pos_atual,
            "pos_nova": pos_nova,
            "efeitos_financeiros": efeitos_fin,
            "observacao": observacao,
            "setor": row.get("SETOR EXERCICIO", "N/A"),
            "chefias": chefes_str,
            "pares": pares_str,
            "funcao_cd": direcao,
            "senha": senha_cpf(row.get("CPF", "000")),
            "afastamentos_periodo": af_per,
            "outros_afastamentos": af_out,
        })

    registros.sort(key=lambda r: (str(r["setor"]), str(r["servidor"])))
    return registros


def formatar_card_markdown(reg, largura=90):
    pares = textwrap.fill(str(reg["pares"]), width=largura, subsequent_indent="")
    return (
        f"**Servidor:** {reg['servidor']}  \n"
        f"**SIAPE:** {reg['siape']}  \n"
        f"**Cargo:** {reg['cargo']}  \n"
        f"**Interstício:** {reg['intersticio_inicio'].strftime('%d/%m/%Y')} a "
        f"{reg['intersticio_fim'].strftime('%d/%m/%Y')}  \n"
        f"**Carreira:** de {reg['pos_atual']} para {reg['pos_nova']}  \n"
        f"**Efeitos financeiros:** "
        +
        (
            f"Sim ({reg['efeitos'].strftime('%d/%m/%Y')})"
            if reg.get("efeitos_financeiros") == "Sim"
            else "Não"
        )
        + "  \n"
        f"**Observação:** {reg.get('observacao', '')}  \n"
        f"**Setor:** {reg['setor']}  \n"
        f"**Chefias na Unidade ({reg['setor']}):** {reg['chefias']}  \n"
        f"**Pares:** {pares}  \n"
        f"**Função/CD:** {reg['funcao_cd']}  \n"
        f"**Senha:** {reg['senha']}  \n"
        f"**Afastamentos (Período):** {reg['afastamentos_periodo']}  \n"
        f"**Outros Afastamentos:** {reg['outros_afastamentos']}"
    )

# @title Relatório
from IPython.display import display, Markdown

registros = gerar_registros_progressao(df, mes_referencia, ano_referencia, afastamentos)
df_relatorio = pd.DataFrame(registros)

# Original report generation follows
display(Markdown(f"### --- RELATÓRIO DE PROGRESSÕES ({mes_referencia:02d}/{ano_referencia}) ---"))

if df_relatorio.empty:
    print(f"Nenhuma progressão identificada para {mes_referencia:02d}/{ano_referencia}.")
else:
    print(f"Encontradas {len(df_relatorio)} progressões.")
    resumo = df_relatorio[["servidor", "siape", "cargo", "pos_atual", "pos_nova", "efeitos_financeiros", "setor", "efeitos"]].copy()
    display(resumo)

    for reg in registros:
        display(Markdown(formatar_card_markdown(reg)))
        display(Markdown("--- --- --- --- --- --- --- --- --- --- --- --- ---"))

    if exportar_excel:
        caminho = f"/content/relatorio_progressoes_{ano_referencia}_{mes_referencia:02d}.xlsx"
        export_df = df_relatorio.copy()
        for col in ["intersticio_inicio", "intersticio_fim", "efeitos"]:
            export_df[col] = pd.to_datetime(export_df[col]).dt.strftime("%d/%m/%Y")
        export_df["afastamentos_periodo"] = export_df["afastamentos_periodo"].str.replace(r"<br>&nbsp;+• ", " | ", regex=True)
        export_df["outros_afastamentos"] = export_df["outros_afastamentos"].str.replace(r"<br>&nbsp;+• ", " | ", regex=True)
        export_df.to_excel(caminho, index=False)
        print(f"Excel salvo em: {caminho}")

Ajustar carreira EBTT para que conversões do formato antigo seja adequado ao formato novo
Ajustar para output de Função/CD somente puxar casos de ocupação de CD